permalink: pretty
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#pygments: true

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Mike Burns"
 
prose:
  metadata:
    "_posts": |
      layout: post
      date: CURRENT_DATETIME
      published: true
