permalink: pretty
highlighter: pygments
#markdown: kramdown
#pygments: true

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Mike Burns"
 
prose:
  metadata:
    "_posts": |
      layout: post
      date: CURRENT_DATETIME
      published: true
