permalink: pretty
#markdown: kramdown
#pygments: true

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Mike Burns"
