permalink: pretty
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#pygments: true
url: http://thepixelguy.com

#pages:
#  permalink: pretty

#posts:
#  permalink: /blog/:categories/:year/:month/:day/:title.html


defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Mike Burns"
 
prose:
  metadata:
    "_posts": |
      layout: post
      date: CURRENT_DATETIME
      published: true
